In [1]:
 # question 1 
    
sequence=[]
for X in range(2000,3200):
    if (X%7==0)and (X%5!=0):
        sequence.append(str(X))
                               
print(', '.join(sequence))

2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199


In [148]:
# question 2

def factorial(n):  
              if n == 1:  
               return n  
              else:  
                return n*factorial(n-1)  
    
x  = int ( input ("Enter  number") )
            
if x < 0:  
    print("negative numbers not accepted")  
elif x == 0:  
    print("factorial of 0 is 1")  
else:  
    print("factorial of",x,"is",factorial(x))  
    
    
       
    
    

Enter  number8
factorial of 8 is 40320


In [35]:
# question 3

Dict = {} 
x  = int ( input ("Enter  number") )
if x <= 0:  
     print("number must be sup or equal to 1")   
else: 
      for i in range(1,x+1):
        Dict[i]= i*(x)
  
    
print(Dict)  





Enter  number5
{1: 5, 2: 10, 3: 15, 4: 20, 5: 25}


In [21]:
# question 4

import math      

c = 50
h = 30

value = []
items=[x for x in input().split(',')]
for d in items:
        value.append(str(int(round(math.sqrt(2*c*float(d)/h)))))
print(','.join(value))   
    
    
    

    
    

100,150,180
18,22,24


In [18]:
# question 5

 


def missing_char(str, n):
       first_part = str[:n] 
       last_part = str[n+1:]
       return first_part + last_part
print(missing_char('kitten', 1))
print(missing_char('kitten', 0))
print(missing_char('kitten', 4))



 




ktten
itten
kittn


In [163]:
# question 6

raw = "g fmnc wms bgblr rpylqjyrc gr zw fylb. rfyrq ufyr amknsrcpq ypc dmp. bmgle gr gl zw fylb gq glcddgagclr ylb rfyr'q ufw rfgq rcvr gq qm jmle. sqgle qrpgle.kyicrpylq() gq pcamkkclbcb. lmu ynnjw ml rfc spj."
table = str.maketrans("abcdefghijklmnopqrstuvwxyz", "cdefghijklmnopqrstuvwxyzab")
raw.translate(table)
    
    
    

"i hope you didnt translate it by hand. thats what computers are for. doing it in by hand is inefficient and that's why this text is so long. using string.maketrans() is recommended. now apply on the url."

In [2]:
# question 7

import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())



Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [3]:
# question 8


import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]
